#!/bin/bash
# sudo shim for cyberxero-toolkit
# Forwards commands to cyberxero-auth

# Path to cyberxero-auth client
CYBERXERO_AUTH="/opt/cyberxero-toolkit/cyberxero-auth"

# Skip sudo flags until we find the command
while [[ "$1" == -* ]]; do
    case "$1" in
        -u|-g|-p|-C|-U)
            shift 2 # Skip flag and argument
            ;;
        --)
            shift
            break
            ;;
        *)
            shift # Skip flag
            ;;
    esac
done

exec "$CYBERXERO_AUTH" "$@"
